@startmindmap
* lib
** main.dart
** app.dart
** config
*** theme
**** light_theme.dart
**** dark_theme.dart
**** theme_constants.dart
*** routes.dart
*** constants.dart
*** api_config.dart
*** env.dart
** core
*** error
**** exceptions.dart
**** failures.dart
*** network
**** api_client.dart
**** socket_client.dart
**** interceptors
***** auth_interceptor.dart
***** error_interceptor.dart
*** utils
**** currency
***** currency_formatter.dart
***** exchange_calculator.dart
**** date_utils.dart
**** validators.dart
**** file_utils.dart
**** location_utils.dart
** data
*** models
**** user
***** user_model.dart
***** user_dto.dart
***** user_settings_model.dart
***** user_verification_model.dart
**** purchase
***** purchase_model.dart
***** purchase_request_model.dart
***** purchase_response_model.dart
***** delivery_model.dart
**** travel
***** travel_model.dart
***** travel_plan_model.dart
***** travel_route_model.dart
***** service_area_model.dart
**** transaction
***** transaction_model.dart
***** payment_model.dart
***** order_model.dart
***** dispute_model.dart
*** repositories
**** user_repository_impl.dart
**** purchase_repository_impl.dart
**** travel_repository_impl.dart
**** auth_repository_impl.dart
**** transaction_repository_impl.dart
*** datasources
**** local
***** user_local_datasource.dart
***** auth_local_datasource.dart
***** purchase_local_datasource.dart
***** secure_storage_helper.dart
***** hive_storage_helper.dart
**** remote
***** api
****** user_api.dart
****** purchase_api.dart
****** travel_api.dart
****** auth_api.dart
***** websocket
****** chat_socket_client.dart
****** socket_event_handler.dart
** domain
*** entities
**** user_entity.dart
**** purchase_entity.dart
**** travel_entity.dart
**** transaction_entity.dart
**** chat_entity.dart
*** repositories
**** i_user_repository.dart
**** i_purchase_repository.dart
**** i_travel_repository.dart
**** i_auth_repository.dart
**** i_transaction_repository.dart
*** usecases
**** auth
***** login_usecase.dart
***** register_usecase.dart
***** verify_email_usecase.dart
**** purchase
***** create_purchase_request_usecase.dart
***** update_purchase_request_usecase.dart
***** get_purchase_history_usecase.dart
**** travel
***** register_travel_plan_usecase.dart
***** update_travel_status_usecase.dart
***** search_available_travels_usecase.dart
** presentation
*** screens
**** auth
***** login_screen.dart
***** register_screen.dart
***** verification_screen.dart
**** home
***** buyer
****** home_screen.dart
****** main_tab_screen.dart
****** price_comparison_screen.dart
***** seller
****** seller_home_screen.dart
****** travel_registration_screen.dart
**** purchase
***** create_request_screen.dart
***** request_list_screen.dart
***** request_detail_screen.dart
**** chat
***** chat_list_screen.dart
***** chat_room_screen.dart
***** notifications_screen.dart
*** widgets
**** common
***** buttons
****** primary_button.dart
****** outline_button.dart
****** icon_button.dart
***** cards
****** info_card.dart
****** product_card.dart
****** travel_card.dart
***** dialogs
****** alert_dialog.dart
****** confirm_dialog.dart
****** loading_dialog.dart
**** specific
***** purchase
****** request_form.dart
****** price_comparison_widget.dart
***** travel
****** travel_form.dart
****** route_selection_widget.dart
***** chat
****** chat_bubble.dart
****** message_input.dart
*** blocs
**** auth
***** auth_bloc.dart
***** auth_event.dart
***** auth_state.dart
**** purchase
***** purchase_bloc.dart
***** purchase_event.dart
***** purchase_state.dart
**** travel
***** travel_bloc.dart
***** travel_event.dart
***** travel_state.dart
** di
*** injection.dart
** gen
*** assets.gen.dart
*** l10n.gen.dart
@endmindmap