@startmindmap
** models
*** auth
**** requests
***** login_request.dart
***** register_request.dart
***** verification_request.dart
**** responses
***** auth_response.dart
***** token_response.dart
***** verification_response.dart
*** user
**** profile
***** user_profile.dart
***** profile_settings.dart
***** verification_status.dart
**** preferences
***** notification_preferences.dart
***** language_preferences.dart
***** currency_preferences.dart
*** purchase
**** request
***** purchase_request.dart
***** request_filter.dart
***** request_status.dart
**** delivery
***** delivery_info.dart
***** tracking_info.dart
***** shipping_details.dart
**** price
***** price_comparison.dart
***** price_history.dart
***** currency_rate.dart
*** travel
**** plan
***** travel_plan.dart
***** route_details.dart
***** schedule.dart
**** service
***** available_service.dart
***** service_restrictions.dart
***** service_pricing.dart
**** capacity
***** weight_capacity.dart
***** volume_capacity.dart
***** restrictions.dart
*** transaction
**** order
***** order_details.dart
***** order_status.dart
***** order_history.dart
**** payment
***** payment_info.dart
***** payment_method.dart
***** escrow_details.dart
**** dispute
***** dispute_case.dart
***** resolution_details.dart
***** evidence_data.dart
*** common
**** base
***** base_model.dart
***** auditable_model.dart
***** trackable_model.dart
**** response
***** api_response.dart
***** pagination_data.dart
***** error_response.dart
**** value_objects
***** money.dart
***** weight.dart
***** location.dart
***** date_range.dart
@endmindmap
